### ISSUE TITLE
Fill in the FIXME's..... what is squid..... :)

### ISSUE THREAD

**Issue by Mwilloughby1982** [genesis-community/squid-genesis-kit#1]

**Comment by cwb124** [comment]
Working on it as we speak...should be updated today.

**Comment by Mwilloughby1982** [comment]
Haha just saw it and was curious and when the doc said I should open an issue I took that as a cue to harass someone :)

Thank you

**Comment by jhunt** [comment]
Merged (finally)!

Apologies for the delay on this one.. 😥
